#######################################################################
# Docker Compose for target container
#
# Description:
#   This is the docker-compose file used to run the target (i.e. the container
#   that will be monitored by the monitor service).
#######################################################################

version: '3.5'

services:
  nginx:
    container_name: nginx-alpine
    image: nginx:1.25.3-alpine-slim
    ports:
      - "127.0.0.1:8080:80"
    expose:
      - "80"
    restart: unless-stopped
